### ISSUE TITLE
MKB_PvE_!Backups_Perks is tagged for PvP

### ISSUE THREAD

**Issue by GabeClark99** [2Pillows/dim_wishlist_splitter#5]
The new list and its Dupes option (aa1f7f2) do not appear when excluding lists tagged for PvP.

![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/8a9c0e56-eaf0-4589-a1b1-908ea5af9a69)

![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/3456572a-7cfd-43fe-b3ec-74893a4b3e68)

**Comment by 2Pillows** [comment]
Thank you for letting me know about this issue. It should be all fixed now. Sorry again for the inconvenience.

When I created the lists, I copied the preceding MKB-only version and added "PvE" to the names and tags. I forgot to remove "_pve_pvp" at the end of the tags, which caused problems with the website filtering.

**Comment by GabeClark99** [comment]
No problem at all. Love this tool, and want it to be the best it can be.
