### ISSUE TITLE
Wishlist Request - MKB_PvE_!Backups

### ISSUE THREAD

**Issue by GabeClark99** [2Pillows/dim_wishlist_splitter#6]
Similar to the existing MKB_PvE_!Backups_Perks, but not limited to just columns three and four. Personally, I'd be using both in conjunction; I'll still use a weapon even if it doesn't roll well in columns one and two, but I'd still like to quickly determine if it did roll well in those columns. 

**Input**

* Only show rolls for Mouse and Keyboard

**Gamemode**

* Only show rolls for PvE

**Roll Type**

* Remove rolls that are tagged as "Backup Rolls"

**Comment by 2Pillows** [comment]
Thank you for the request, just added it.

Thanks again for all your contributions to this project. Hope you have fun with The Final Shape!
