### ISSUE TITLE
MKB_PvE_!Backups_Perks does not appear when filtering for Perks

### ISSUE THREAD

**Issue by GabeClark99** [2Pillows/dim_wishlist_splitter#7]
**Describe the bug**
On the website, MKB_PvE_!Backups_Perks does not appear when the following filter is applied: include "3rd and 4th Column Perks." 

**To Reproduce**
1. Go to the wishlist splitter website.
2. Click on "Mouse and Keyboard" once, "PVP" twice, "No Backup Rolls" once, and "3rd and 4th Column Perks" once.
3. In the resulting list, observe that the entry for MKB_PvE_!Backups_Perks is not present.

**Expected behavior**
The entry for MKB_PvE_!Backups_Perks will be displayed in the list.

**Screenshots**

![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/3feb5b85-dc4c-4436-be2b-8af616cb673c)

![image](https://github.com/2Pillows/dim_wishlist_splitter/assets/54868591/ba89f7ff-dab3-4d50-8927-3330ad319384)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version: e617820

**Additional context**
Notably, the Dupes version of the wishlist (MKB_PvE_!Backups_Perks_Dupes) is displayed when the mentioned filters are applied.

**Comment by 2Pillows** [comment]
Thank you, I had a typo of "perk" instead of "perks" for that roll's tag. Should be fixed with next push.
